---
- name: Install MySQL
  gather_facts: false
  hosts: dataservers
  vars:
    ansible_ssh_user: safalkon
  become: yes

  pre_tasks:
    - name: Validating the ssh port is open and
      wait_for:
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        port: 22
        delay: 5
        timeout: 300
        state: started
        search_regex: OpenSSH
    
  tasks:
    - name: Install Python MySQL client
      apt:
        name: python3-pymysql
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL server (latest available)
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set root password
      mysql_user:
        name: root
        password: "root123"
        check_implicit_admin: yes
        login_unix_socket: /var/run/mysqld/mysqld.sock
        column_case_sensitive: false